name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * MON"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test
        run: |
          go test -v ./...
